#cloud-config, install docker, update, add user
runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh; sh get-docker.sh
  - sudo apt update && apt upgrade  
  - sudo usermod -aG docker $USER

