#cloud-config
#usual config goes here

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh; sh get-docker.sh

# Add default auto created user to docker group
system_info:
    default_user:
        groups: [docker]

