#!/bin/bash
for ((i=1 ; i<=999999; i++))
do
  quote=$(echo $(curl -s https://geek-jokes.sameerkumar.website/api) | sed "s/^\([\"']\)\(.*\)\1\$/\2/g")
  echo "Sending to $1 | $quote"
  curl --silent --output /dev/null -G "http://$1/input" --data-urlencode "data=$quote"
  sleep 2
done

